#!/bin/bash
echo "insight activing..."
sleep 3
echo "run operation saboteur..."
sleep 0.5
echo "sudo apt-get install insight"
sleep 0.05
echo "password:"
sleep 1.5
echo "Reading package lists... Done"
sleep 0.1
echo "Building dependency tree"
sleep 0.1
echo "Reading state information... Done"
sleep 0.05
echo "The following NEW packages will be installed:"
sleep 0.05
echo "  insight"
sleep 0.05
echo "  0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded."
sleep 0.1
echo "  Need to get 121kB of archives."
sleep 0.05
echo "  After unpacking 438kB of additional disk space will be used."
sleep 0.1
echo "  Get:1 http://us.archive.kog.com edgy/main insight 2.0.4-0kog [121kB]"
sleep 0.1
echo "  Fetched 121kB in 0s (246kB/s)"
echo "Selecting previously deselected package insight."
sleep 0.05
echo "(Reading database ... 31396 files and directories currently installed.)"
sleep 0.1
echo "Unpacking insight (from .../insight.1.4-0kog.deb) ..."
sleep 0.1
echo "Setting up insight (2.0.4-0kog) ..."
sleep 0.05
echo "Install success"
sleep 1
echo "sudo find ~ -name lume"
sleep 2
a.out
